# Generated by Django 4.2.16 on 2024-11-11 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('origin_country', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
        migrations.AddField(
            model_name='product',
            name='skin_type',
            field=models.CharField(choices=[('All', 'Mọi loại da'), ('Dry', 'Da khô'), ('Oily', 'Da dầu'), ('Sensitive', 'Da nhạy cảm'), ('Normal', 'Da thường')], default='All', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Chờ xử lý'), ('Shipped', 'Đang giao'), ('Delivered', 'Đã giao'), ('Cancelled', 'Đã hủy')], default='Pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.brand'),
        ),
    ]
